# Generated by Django 5.0.3 on 2024-03-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
