# Generated by Django 5.0.3 on 2024-04-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_product_rating_productrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRate',
        ),
    ]
