# Generated by Django 5.0.3 on 2024-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_profil_confirmation_code_profil_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='confirmation_code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
